name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: Run Rust Unit Tests
        run: cargo test

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.5'

      - name: Run Python Unit Tests
        run: python3 tests/python/runner.py

  fuzzing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Nightly
        run: rustup toolchain install nightly --profile minimal
      - name: Install cargo-fuzz
        run: cargo install cargo-fuzz
      - name: Run Fuzzing Tests
        run: |
          for target in $(cargo fuzz list); do
            cargo +nightly fuzz run $target -- -runs=10000 -max_total_time=30
          done
